### ISSUE TITLE
README: Dependancy is incorrect

### ISSUE THREAD

**Issue by leocrank** [m0wfo/cups#20]
Specifically this line in the readme:
`sudo apt-get install libcupsys2-dev`

libcupsys2-dev does not exist in the repositories.

This should instead read:
`sudo apt-get install libcups-dev`

See this link for confirmation:
https://packages.debian.org/squeeze/libcupsys2-dev

**Comment by m0wfo** [comment]
@leocrank done! Thanks for letting me know
