### ISSUE TITLE
Couldn't find CUPS libraries on your system. Check they're installed and in your path. (CentOS 6.5)

### ISSUE THREAD

**Issue by bigtunacan** [m0wfo/cups#22]
I'm getting the "Couldn't find CUPS libraries on your system. Check they're installed and in your path." error on CentOS 6.5.  Does anyone know what yum packages or other setup is required for CentOS 6.5?

So far I have tried installing the `cups` and `cups-libs` packages.

**Comment by rafaeldbernardes** [comment]
You should install required cups libraries as mentioned in cups installation :

**Comment by m0wfo** [comment]
@bigtunacan as you can tell I haven't looked at this for a while; if this fixes the issue, let me know

**Comment by medexdev** [comment]
on centos 6.5, you need to install the following three.
cups
cups-devel
cups-libs
